-- SIGAF · Precios 2026 (MAR-DIC) Derma Body — contrato 050GYR032N12025-195-00
-- Fuente: 'Precios 2026 AGS.xlsx'. Inserta la lista o actualiza el precio si ya existe.
begin;

-- Limpiar la lista previa de ESTE contrato (verificado: 0 facturas ligadas) para dejar exactamente los 120 precios 2026.
delete from contrato_servicios cs using contratos ct
where cs.contrato_id = ct.id and ct.numero_interno = '050GYR032N12025-195-00';

insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('ACEITE DE ALMENDRAS 1 Mililitro', 0.39),
  ('ACICLOVIR CREMA 1 Gramo', 0.01),
  ('ACIDO ACETICO 1 Mililitro', 0.01),
  ('ACIDO ASCORBICO 1 Gramo', 0.01),
  ('ACIDO CITRICO 1 Gramo', 0.17),
  ('ACIDO LACTICO 1 Mililitro', 0.01),
  ('ACIDO RETINOICO 0.05% 1 Gramo', 0.12),
  ('ACIDO SALICILICO 1 Gramo', 0.17),
  ('ACIDO TRICLOROACETICO 40 % 1 Mililitro', 0.01),
  ('ACIDO TRICLOROACETICO 50 % 1 Mililitro', 0.01),
  ('ACIDO TRICLOROACETICO 10 % 1 Mililitro', 0.01),
  ('ACIDO TRICLOROACETICO 20 % 1 Mililitro', 0.01),
  ('ACIDO TRICLOROACETICO 30 % 1 Mililitro', 0.01),
  ('ACIDO TRICLOROACETICO A SATURACION 1 Mililitro', 0.01),
  ('AGUA DE HAMMAMELIS 1 Mililitro', 0.13),
  ('AGUA DE ROSAS 1 Mililitro', 0.05),
  ('AGUA DE VEGETO 1 Mililitro', 0.01),
  ('AGUA DESTILADA 1 Mililitro', 0.03),
  ('AGUA SEGUNDA DE CAL 1 Mililitro', 0.01),
  ('ALCANFOR 1 Gramo', 0.01),
  ('ALCOHOL DE 50° 1 Mililitro', 0.04),
  ('ALCOHOL DE 70° 1 Mililitro', 0.06),
  ('ALQUITRAN DE HULLA 1 Gramo', 0.02),
  ('AMOROLFINA 1 Mililitro', 0.01),
  ('AVENA COLOIDAL LOCION 1 Mililitro', 0.01),
  ('AVENA COLOIDAL POMADA 1 Gramo', 0.09),
  ('AZUFRE 1 Gramo', 0.11),
  ('BALSAMO DE PERU 1 Gramo', 0.01),
  ('BENZONATATO DE BENCILO EMULSION 1 Mililitro', 0.01),
  ('BETAMETASONA LOCION 1 Mililitro', 0.61),
  ('BETAMETASONA UNGUENTO 1 Gramo', 0.66),
  ('BICARBONATO DE SODIO 1 Gramo', 1.59),
  ('CAFEINA (capsula 10 mg) pieza', 0.01),
  ('CALAMINA 1 Gramo', 0.1),
  ('CALCIPOTRIOL UNGUENTO 1 Gramo', 1.15),
  ('CALCIPOTRIOL / BETAMETASONA UNGÜENTO TUBO 30 gr. 1 pieza', 0.01),
  ('CARBON ACTIVADO 1 Kilogramo', 0.01),
  ('CARBON ACTIVADO 1 Miligramo', 0.01),
  ('CARBONATO DE CALCIO 1 gr. 1 pieza', 3.05),
  ('CARBONATO DE CALCIO 500 mgs 1 pieza', 1.45),
  ('CITRATO DE POTASIO 1 Gramo', 0.37),
  ('CITRATO DE SODIO 1 Gramo', 0.02),
  ('CLINDAMICINA LOCION 1 Mililitro', 0.02),
  ('CLINDAMICINA GEL 1 Gramo', 0.73),
  ('CLORURO DE ALUMINIO 1 Mililitro', 0.01),
  ('COLD CREAM 1 Gramo', 0.69),
  ('COLODION ELASTICO 1 Gramo', 0.18),
  ('CREMA DE ALMENDRAS 1 Gramo', 0.5),
  ('CREMA DE AVENA 1 Gramo', 0.39),
  ('CREMA DE AVENA PIELES INTOLERANTES 1 Gramo', 0.04),
  ('CREMA DE MANZANILLA 1 Gramo', 0.39),
  ('CREMA PIELES INTOLERANTES 1 Gramo', 0.78),
  ('DIMETILSULFOXIDO O DOMOSO EN SOLUCION ACUOSA 1 Mililitro', 0.01),
  ('DIOXIDO DE TITANIO 1 Gramo', 0.01),
  ('ERITROMICINA SOLUCION 1 Mililitro', 0.01),
  ('ESENCIA DE BERGAMOTA 1 Mililitro', 0.01),
  ('ESENCIA DE LIMA 1 Mililitro', 0.58),
  ('ETER 1 Mililitro', 0.01),
  ('FENOL 1 Mililitro', 0.01),
  ('GLICERINA 1 Gramo', 0.03),
  ('GLICEROLADO NEUTRO DE ALMIDON 1 Gramo', 0.12),
  ('HIDROCORTISONA CREMA 1 Gramo', 0.13),
  ('HIDROQUINONA QUIMICAMENTE PURA 1 Gramo', 0.46),
  ('JARABE DE GROSELLA 1 Mililitro', 0.03),
  ('KETANSERINA GEL 1 Gramo', 2.79),
  ('KETOCONAZOL CREMA 1 Gramo', 0.12),
  ('KETOCONAZOL TALCO 1 Gramo', 0.01),
  ('LACTOSA 1 Kilogramo', 0.23),
  ('LANOLINA 1 Gramo', 0.47),
  ('LICOR DE HOFFMAN 1 Mililitro', 0.11),
  ('LINDANO 1 Gramo', 0.01),
  ('LINIMENTO OLEOCALCAREO 1 Mililitro', 0.3),
  ('LOCION DE CALAMINA 1 Mililitro', 0.01),
  ('LOCION DE MANZANILLA 1 Mililitro', 0.01),
  ('LOCION DE RESORCINA 1 Mililitro', 0.01),
  ('MAGNECIA CALCINADA, sobre 1 Gramo', 0.01),
  ('MELADININA POMADA 1 Gramo', 0.01),
  ('MENTOL 1 Gramo', 0.01),
  ('METRONIDAZOL CREMA 1 Gramo', 0.32),
  ('METRONIDAZOL GEL. 1 Gramo', 0.36),
  ('MINOXIDIL 2-5% 1 Mililitro', 0.22),
  ('MOMETASONA SOLUCION 1 Mililitro', 0.45),
  ('MOMETASONA UNGUENTO 1 Gramo', 0.62),
  ('MUPIROCINA UNGUENTO 1 Gramo', 1.66),
  ('NITRATO DE ECONAZOL TALCO 1 Gramo', 0.01),
  ('OXIDO DE ZINC 1 Gramo', 0.34),
  ('PERMANGANATO DE POTASIO, sobres 0.1 gr 1 Pieza', 0.01),
  ('PERMETRINA 1 Gramo', 0.01),
  ('PEROXIDO DE BENZOILO 0.5% 1 Gramo', 0.39),
  ('PIMECROLIMUS CREMA 1 Gramo', 3.82),
  ('PODOFILINA 1 Gramo', 1),
  ('POMADA DE AVENA COLOIDAL 1 Gramo', 0.02),
  ('PRESPIR 1 Mililitro', 0.01),
  ('PROPILENGLICOL 1 Mililitro', 0.01),
  ('PROTECTOR SOLAR GEL 1 Gramo', 0.77),
  ('PROTECTOR SOLAR ULTRA CREMA 1 Gramo', 0.81),
  ('RESORCINA 1 Gramo', 0.01),
  ('SHAMPOO DE ALQUITRAN DE HULLA DEL 1 AL 5 % 1 Mililitro', 0.21),
  ('SHAMPOO KETOCONAZOL 1 Mililitro', 0.21),
  ('SHAMPOO PROPIONATO DE CLOBETAZOL 1 Mililitro', 0.2),
  ('SUCRALFATO CREMA 1 Gramo', 0.01),
  ('SUCRALFATO POMADA 1 Gramo', 0.01),
  ('SULFATO DE COBRE sobre 1 gr 1 Pieza', 0.01),
  ('TACROLIMUS UNGÜENTO 1 Gramo', 3.64),
  ('TALCO 1 Gramo', 0.03),
  ('TANINO 1 Gramo', 0.01),
  ('TAZAROTENO CREMA 0.1% 1 Gramo', 0.01),
  ('TAZAROTENO GEL 0.05% 1 Gramo', 0.01),
  ('TINTURA DE MANZANILLA 1 Mililitro', 0.01),
  ('TINTURA DE MELADININA 1 Mililitro', 0.01),
  ('TINTURA DE MILLAN 1 Mililitro', 0.01),
  ('TINTURA FLORAL 1 Mililitro', 0.01),
  ('TINTURA TUCAL 1 Mililitro', 0.01),
  ('TINTURA YODADA 1 Mililitro', 0.01),
  ('TROMANTADINA GEL 1 Gramo', 0.01),
  ('UREA 1 Gramo', 0.38),
  ('VASELINA 1 Gramo', 1.33),
  ('VIOFORMO 1 Gramo', 0.01),
  ('XILOL 1 Gramo', 0.01),
  ('YODURO DE POTASIO 1 Gramo', 0.01)
) as v(servicio, precio)
join contratos ct on ct.numero_interno = '050GYR032N12025-195-00'
on conflict (contrato_id, nombre_servicio) do update set precio_unitario = excluded.precio_unitario;

commit;

-- Verificación:
-- select count(*), min(precio_unitario), max(precio_unitario) from contrato_servicios cs join contratos ct on ct.id=cs.contrato_id where ct.numero_interno='050GYR032N12025-195-00';
