-- SIGAF · contrato_servicios Cuadro Básico (medicamentos usados, precio del catálogo cat). Idempotente.
begin;

-- CB-51211010 (7 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('DESINFECTANTE Y BLANQUEADOR LIQUIDO, FORMULADO CON HIPOCLORITO DE SODIO A UNA CONCENTRACION DEL 6.0% MINIMO DE', 346.08),
  ('JABON LIQUIDO PARA LAVADO DE MANOS PARA USO INDUSTRIAL, INSTITUCIONAL Y HOSPITALARIO. CUYAS ESPECIFICACIONES T', 518.15),
  ('LIMPIADOR LIQUIDO DESENGRASANTE, LIQUIDO COLOR AZUL MARINO, PARA DISOLVER Y REMOVER MANCHAS DE GRASA Y ACEITE ', 753.07),
  ('JABON LIQUIDO NEUTRO PARA LIMPIEZA DE PISOS, PAREDES Y VIDRIOS. CUYAS ESPECIFICACIONES TECNICAS DEBEN CUMPLIR ', 705.56),
  ('MECHUDO CON SUJETADOR DE PLASTICO O METALICO CON ROSCA HEMBRA PARA BASTON INTERCAMBIABLE, PESO DEL MECHUDO 400', 74.1),
  ('DETERGENTE, DESINFECTANTE Y DESODORANTE PARA LIMPIEZA DE BAÑOS Y SU MOBILIARIO A BASE DE CLORURO DE BENZALCONI', 740.74),
  ('REPUESTO PARA MECHUDO, PESO DEL MECHUDO 400 GRAMOS, CAJA DE CARTON CON 40 PIEZAS. CUYAS ESPECIFICACIONES TECNI', 1260.18)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51211010'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

-- CB-51251002 (73 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('LIDOCAINA, EPINEFRINA SOLUCION INYECTABLE AL 2% CADA FRASCO AMPULA CONTIENE: CLORHIDRATO DE LIDOCAINA 1 G EPIN', 158),
  ('CICLOSPORINA SOLUCION OFTALMICA CADA ML CONTIENE: CICLOSPORINA A 1.0 MG; ENVASE CON FRASCO GOTERO CON 5 ML.', 659.11),
  ('VANCOMICINA SOLUCION INYECTABLE CADA FRASCO AMPULA CON POLVO CONTIENE: CLORHIDRATO DE VANCOMICINA EQUIVALENTE ', 19.94),
  ('BUDESONIDA. SUSPENSION PARA NEBULIZAR. CADA ENVASE CONTIENE: BUDESONIDA (MICRONIZADA) 0.250 MG. ENVASE CON 20 ', 172.86),
  ('ENOXAPARINA. SOLUCION INYECTABLE CADA JERINGA CONTIENE: ENOXAPARINA SODICA 20 MG. ENVASE CON 10 JERINGAS. DE 0', 457),
  ('VASOPRESINA. SOLUCION INYECTABLE CADA AMPOLLETA CONTIENE: VASOPRESINA 20 UI ENVASE CON UNA AMPOLLETA.', 102.05),
  ('LIDOCAINA SOLUCION INYECTABLE AL 1% CADA FRASCO AMPULA CONTIENE: CLORHIDRATO DE LIDOCAINA 500 MG ENVASE CON 5 ', 88.1),
  ('OLANZAPINA SOLUCION INYECTABLE CADA FRASCO AMPULA CON LIOFILIZADO CONTIENE: OLANZAPINA 10 MG ENVASE CON UN FRA', 156.77),
  ('ENOXAPARINA SOLUCION INYECTABLE CADA JERINGA CONTIENE ENOXAPARINA SODICA 60 MG ENVASE CON 2 JERINGAS DE 0.6 ML', 105.33),
  ('DOLUTEGRAVIR / ABACAVIR / LAMIVUDINA. TABLETA. CADA TABLETA CONTIENE: DOLUTEGRAVIR SODICO EQUIVALENTE A 50 MG ', 3037.28),
  ('BROMURO DE TIOTROPIO. POLVO. CADA CAPSULA CONTIENE: BROMURO DE TIOTROPIO MONOHIDRATADO EQUIVALENTE A 18 MICROG', 253.75),
  ('SEVOFLURANO. LIQUIDO O SOLUCION. CADA ENVASE CONTIENE: SEVOFLURANO 250 ML. ENVASE CON 250 ML DE LIQUIDO O SOLU', 957.18),
  ('ATORVASTATINA/ EZETIMIBA. CAPSULA O TABLETA CADA CAPSULA O TABLETA CONTIENE: ATORVASTATINA CALCICA TRIHIDRATO ', 284.84),
  ('DICLOXACILINA CAPSULA O COMPRIMIDO CADA CAPSULA O COMPRIMIDO CONTIENE: DICLOXACILINA SODICA 500 MG ENVASE CON ', 68.8),
  ('PROGESTERONA. CAPSULA O PERLA CADA CAPSULA O PERLA CONTIENE: PROGESTERONA 200 M G ENVASE CON 15 CAPSULAS O PER', 130),
  ('LEVETIRACETAM. SOLUCION ORAL CADA 100 ML CONTIENEN: LEVETIRACETAM 10 G ENVASE CON 300 ML (100 MG/ML).', 101.01),
  ('LEVOCARNITINA. SOLUCION INYECTABLE CADA AMPOLLETA CONTIENE: LEVOCARNITINA 1 G ENVASE CON 5 AMPOLLETAS DE 5 ML.', 46),
  ('ACIDO URSODEOXICOLICO CAPSULA CADA CAPSULA CONTIENE: ACIDO URSODEOXICOLICO 250 MG ENVASE CON 50 CAPSULAS.', 151.81),
  ('ERTAPENEM. SOLUCION INYECTABLE CADA FRASCO AMPULA CON LIOFILIZADO CONTIENE: ERTAPENEM SODICO EQUIVALENTE A 1 G', 210),
  ('BUPIVACAINA. SOLUCION INYECTABLE. CADA AMPOLLETA CONTIENE: CLORHIDRATO DE BUPIVACAINA 15 MG. DEXTROSA ANHIDRA ', 18.12),
  ('AMOXICILINA - ACIDO CLAVULANICO. TABLETA. CADA TABLETA CONTIENE: AMOXICILINA TRIHIDRATADA EQUIVALENTE A 500 MG', 43.04),
  ('TRINITRATO DE GLICERILO SOLUCION INYECTABLE CADA FRASCO AMPULA CONTIENE: TRINITRATO DE GLICERILO 50 MG ENVASE ', 347.44),
  ('MISOPROSTOL. TABLETA. CADA TABLETA CONTIENE: MISOPROSTOL 200 MICROGRAMOS. ENVASE CON 12 TABLETAS.', 120.74),
  ('MONTELUKAST COMPRIMIDO RECUBIERTO CADA COMPRIMIDO CONTIENE: MONTELUKAST SODICO EQUIVALENTE A 10 MG DE MONTELUK', 19.93),
  ('MOMETASONA SUSPENSION PARA INHALACION CADA 100 ML CONTIENE: FUROATO DE MOMETASONA MONOHIDRATADA EQUIVALENTE A ', 31.99),
  ('EZETIMIBA. TABLETA. CADA TABLETA CONTIENE: EZETIMIBA 10 MG. ENVASE CON 30 TABLETAS.', 23.23),
  ('CLINDAMICINA CAPSULA CADA CAPSULA CONTIENE: CLORHIDRATO DE CLINDAMICINA EQUIVALENTE A 300 MG DE CLINDAMICINA. ', 19.01),
  ('DORAVIRINA. TABLETA. CADA TABLETA CONTIENE: DORAVIRINA 100 MG. CAJA CON FRASCO CON 30 TABLETAS.', 2113.2),
  ('MESALAZINA GRAGEA CON CAPA ENTERICA O TABLETA DE LIBERACION PROLONGADA CADA GRAGEA CON CAPA ENTERICA O TABLETA', 193.5),
  ('PRAZOSINA CAPSULA O COMPRIMIDO CADA CAPSULA O COMPRIMIDO CONTIENE: CLORHIDRATO DE PRAZOSINA EQUIVALENTE A 1 MG', 15.75),
  ('OXIBUTININA TABLETA CADA TABLETA CONTIENE: CLORURO DE OXIBUTININA 5 MG ENVASE CON 30 TABLETAS.', 68.59),
  ('HIDROXOCOBALAMINA SOLUCION INYECTABLE CADA AMPOLLETA O FRASCO AMPULA CON SOLUCION O LIOFILIZADO CONTIENE: HIDR', 10.52),
  ('NISTATINA SUSPENSION ORAL CADA FRASCO CON POLVO CONTIENE: NISTATINA 2 400 000 UI ENVASE PARA 24 ML.', 14.61),
  ('CONCENTRADO DE PROTEINAS HUMANAS COAGULABLES. SOLUCION. CADA ML DE SOLUCION RECONSTITUIDA CONTIENE: FIBINOGENO', 5555.24),
  ('CONCENTRADO DE PROTEINAS HUMANAS COAGULABLES SOLUCION CADA FRASCO AMPULA 1 CONTIENE: LIOFILIZADO TOTAL DE FIBR', 6175.25),
  ('ACETILCISTEINA SOLUCION AL 20% CADA AMPOLLETA CONTIENE: ACETILCISTEINA 400 MG ENVASE CON 5 AMPOLLETAS CON 2 ML', 1528.2),
  ('AMPICILINA TABLETA O CAPSULA CADA TABLETA O CAPSULA CONTIENE: AMPICILINA ANHIDRA O AMPICILINA TRIHIDRATADA EQU', 36.61),
  ('TOLTERODINA. TABLETA. CADA TABLETA CONTIENE: L TARTRATO DE TOLTERODINA 2 MG. ENVASE CON 28 TABLETAS.', 19.81),
  ('ACIDO ACETILSALICILICO, TABLETAS CADA TABLETA CONTIENE: ACIDO ACETILSALICILICO 100 MG CON O SIN RECUBRIMIENTO.', 42.09),
  ('LEVETIRACETAM TABLETA CADA TABLETA CONTIENE: LEVETIRACETAM 500 MG ENVASE CON 60 TABLETAS.', 46.84),
  ('OXCARBAZEPINA SUSPENSION ORAL CADA 100 ML CONTIENEN: OXCARBAZEPINA 6 G ENVASE CON 100 ML.', 141.08),
  ('SEMAGLUTIDA TABLETA LA TABLETA CONTIENE: SEMAGLUTIDA 14.0 MG GLP-1 DE ORIGEN ADN RECOMBINANTE. CAJA DE CARTON ', 1685),
  ('ENOXAPARINA. SOLUCION INYECTABLE CADA JERINGA CONTIENE: ENOXAPARINA SODICA 40 MG. ENVASE CON 10 JERINGAS. DE 0', 661.15),
  ('ACIDO ALENDRONICO TABLETA O COMPRIMIDO CADA TABLETA O COMPRIMIDO CONTIENE ALENDRONATO DE SODIO EQUIVALENTE A 1', 9),
  ('ACIDO ACETILSALICILICO TABLETA SOLUBLE O EFERVESCENTE CADA TABLETA SOLUBLE O EFERVESCENTE CONTIENE: ACIDO ACET', 8.97),
  ('CALCIO COMPRIMIDO EFERVESCENTE CADA COMPRIMIDO CONTIENE: LACTATO GLUCONATO DE CALCIO 2.94 G CARBONATO DE CALCI', 21.07),
  ('GENTAMICINA SOLUCION INYECTABLE CADA AMPOLLETA CONTIENE: SULFATO DE GENTAMICINA EQUIVALENTE A 80 MG DE GENTAMI', 5),
  ('OSELTAMIVIR CAPSULA CADA CAPSULA CONTIENE: OSELTAMIVIR 75.0 MG ENVASE CON 10 CAPSULAS.', 45.08),
  ('DOBUTAMINA SOLUCION INYECTABLE CADA AMPOLLETA CONTIENE: CLORHIDRATO DE DOBUTAMINA EQUIVALENTE A 250 MG DE DOBU', 133.1),
  ('METOTREXATO. SOLUCION INYECTABLE CADA FRASCO AMPULA CON LIOFILIZADO O SOLUCION CONTIENE: METOTREXATO SODICO EQ', 446.8),
  ('EMPAGLIFLOZINA. TABLETA. CADA TABLETA CONTIENE: EMPAGLIFLOZINA 25 MG ENVASE CON 30 TABLETAS.', 489.89),
  ('CLORURO DE SODIO SOLUCION INYECTABLE CADA 100 ML CONTIENEN: CLORURO DE SODIO 900 MG AGUA INYECTABLE 100 ML ENV', 18.77),
  ('AGUA INYECTABLE SOLUCION INYECTABLE CADA ENVASE CONTIENE: AGUA INYECTABLE 500 ML ENVASE CON 500 ML.', 11.15),
  ('FOSFATO Y CITRATO DE SODIO SOLUCION CADA 100 ML CONTIENEN: FOSFATO MONOSODICO 12 G CITRATO DE SODIO 10 G ENVAS', 26.03),
  ('BUDESONIDA. SUSPENSION PARA NEBULIZAR CADA ENVASE CONTIENE: BUDESONIDA (MICRONIZADA) 0.500 MG. ENVASE CON 20 E', 169.17),
  ('PREGABALINA CAPSULA CADA CAPSULA CONTIENE: PREGABALINA 75 MG ENVASE CON 28 CAPSULAS', 16.6),
  ('ZOLMITRIPTANO. TABLETAS DISPERSABLES. CADA TABLETA DISPERSABLE CONTIENE: ZOLMITRIPTANO 2.5 MG. ENVASE CON 2 TA', 3.63),
  ('VECURONIO SOLUCION INYECTABLE CADA FRASCO AMPULA CON LIOFILIZADO CONTIENE: BROMURO DE VECURONIO 4 MG ENVASE CO', 1090.89),
  ('KETOPROFENO. CAPSULA CADA CAPSULA CONTIENE: KETOPROFENO 100 MG ENVASE CON 15 CAPSULAS.', 20.31),
  ('TOBRAMICINA, SOLUCION OFTALMICA. CADA ML. CONTIENE: SULFATO DE TOBRAMICINA EQUIVALENTE A 3.0 MG DE TOBRAMICINA', 110),
  ('PLANTAGO PSYLLIUM POLVO CADA 100 G CONTIENEN: POLVO DE CASCARA DE SEMILLA DE PLANTAGO PSYLLIUM 49.7 G ENVASE C', 74.28),
  ('ACIDO ASCORBICO TABLETA CADA TABLETA CONTIENE: ACIDO ASCORBICO 100 MG ENVASE CON 20 TABLETAS.', 13),
  ('TERIPARATIDA. SOLUCION INYECTABLE CADA MILILITRO CONTIENE: TERIPARATIDA 250MICROGRAMOS ENVASE CON PLUMA CON CA', 3164.67),
  ('METOPROLOL TABLETA CADA TABLETA CONTIENE: TARTRATO DE METOPROLOL 100 MG ENVASE CON 20 TABLETAS.', 5.79),
  ('DICLOXACILINA SUSPENSION ORAL CADA 5 ML CONTIENEN: DICLOXACILINA SODICA 250 MG ENVASE CON POLVO PARA 60 ML Y D', 19.07),
  ('PINAVERIO. TABLETA. CADA TABLETA CONTIENE: BROMURO DE PINAVERIO 100 MG. ENVASE CON 28 TABLETAS.', 17.08),
  ('EVOLOCUMAB. SOLUCION INYECTABLE CADA JERINGA PRELLENADA CONTIENE: EVOLOCUMAB 140 MG ENVASE CON UNA PLUMA PRECA', 2727.59),
  ('DULOXETINA. CAPSULA DE LIBERACION RETARDADA. CADA CAPSULA DE LIBERACION RETARDADA CONTIENE: CLORHIDRATO DE DUL', 25.8),
  ('SEMAGLUTIDA TABLETA LA TABLETA CONTIENE: SEMAGLUTIDA 3.0 MG GLP-1 DE ORIGEN ADN RECOMBINANTE. CAJA DE CARTON C', 1.01),
  ('VALPROATO DE MAGNESIO TABLETA CON CUBIERTA O CAPA ENTERICA O TABLETA DE LIBERACION RETARDADA CADA TABLETA CONT', 32.21),
  ('LEVETIRACETAM TABLETA CADA TABLETA CONTIENE: LEVETIRACETAM 1 000 MG ENVASE CON 30 TABLETAS.', 47.75),
  ('SACUBITRILO VALSARTAN. COMPRIMIDO. CADA COMPRIMIDO CONTIENE: SACUBITRILO VALSARTAN SODICO HIDRATADO EQUIVALENT', 353.81),
  ('BECLOMETASONA/ FORMOTEROL/ GLICOPIRRONIO AEROSOL CAJA DE CARTON CON FRASCO Y DISPOSITIVO INHALADOR CON CONTADO', 363.09)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51251002'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

-- CB-51251003 (2 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('FORMULA PARA LACTANTES (SUCEDANEO DE LECHE HUMANA DE TERMINO). POLVO O LIQUIDO. ENERGIA: 100ML 60 KCAL - 70 KC', 39.9),
  ('FORMULA DE CONTINUACION. POLVO O LIQUIDO. ENERGIA: 100ML 60 KCAL - 85 KCAL, ENERGIA: 100ML 250 KJ - 355 KJ, VI', 38.98)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51251003'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

-- CB-51251005 (18 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('HALOPERIDOL. SOLUCION ORAL. CADA ML CONTIENE: HALOPERIDOL 2 MG. ENVASE CON GOTERO INTEGRAL CON 15 ML.', 40.44),
  ('BUPRENORFINA SOLUCION INYECTABLE CADA AMPOLLETA O FRASCO AMPULA CONTIENE: CLORHIDRATO DE BUPRENORFINA EQUIVALE', 22),
  ('TRAMADOL. SOLUCION INYECTABLE. CADA AMPOLLETA CONTIENE: CLORHIDRATO DE TRAMADOL 100 MG. ENVASE CON 5 AMPOLLETA', 15.37),
  ('ALPRAZOLAM TABLETA CADA TABLETA CONTIENE: ALPRAZOLAM 2.0 MG ENVASE CON 30 TABLETAS.', 13.35),
  ('FENTANILO SOLUCION INYECTABLE CADA AMPOLLETA O FRASCO AMPULA CONTIENE: CITRATO DE FENTANILO EQUIVALENTE A 0.5 ', 262.13),
  ('BUPRENORFINA PARCHE CADA PARCHE CONTIENE: BUPRENORFINA 5 MG ENVASE CON 4 PARCHES. VELOCIDAD NOMINAL DE LIBERAC', 339.67),
  ('HIDROXIZINA GRAGEA O TABLETA CADA GRAGEA O TABLETA CONTIENE: CLORHIDRATO DE HIDROXIZINA 10 MG ENVASE CON 30 GR', 10.68),
  ('ALPRAZOLAM. TABLETA CADA TABLETA CONTIENE: ALPRAZOLAM 0.25 MG ENVASE CON 30 TABLETAS.', 14.11),
  ('LITIO TABLETA CADA TABLETA CONTIENE: CARBONATO DE LITIO 300 MG ENVASE CON 50 TABLETAS.', 280.66),
  ('BUPRENORFINA PARCHE CADA PARCHE CONTIENE: BUPRENORFINA 10 MG ENVASE CON 4 PARCHES. VELOCIDAD NOMINAL DE LIBERA', 583.64),
  ('ERGOMETRINA SOLUCION INYECTABLE CADA AMPOLLETA CONTIENE: MALEATO DE ERGOMETRINA 0.2 MG ENVASE CON 50 AMPOLLETA', 200.25),
  ('MIDAZOLAM SOLUCION INYECTABLE CADA AMPOLLETA CONTIENE: CLORHIDRATO DE MIDAZOLAM EQUIVALENTE A 15 MG DE MIDAZOL', 26.12),
  ('CLONAZEPAM TABLETA CADA TABLETA CONTIENE: CLONAZEPAM 2 MG ENVASE CON 30 TABLETAS.', 8.59),
  ('CLONAZEPAM SOLUCION CADA ML CONTIENE: CLONAZEPAM 2.5 MG ENVASE CON 10 ML Y GOTERO INTEGRAL.', 23.79),
  ('DIAZEPAM TABLETA CADA TABLETA CONTIENE: DIAZEPAM 10 MG ENVASE CON 20 TABLETAS.', 16.63),
  ('IMIPRAMINA GRAGEA O TABLETA CADA GRAGEA O TABLETA CONTIENE: CLORHIDRATO DE IMIPRAMINA 25 MG ENVASE CON 20 GRAG', 5.28),
  ('MIDAZOLAM. SOLUCION INYECTABLE CADA AMPOLLETA CONTIENE CLORHIDRATO DE MIDAZOLAM EQUIVALENTE A 50 MG DE MIDAZOL', 83.66),
  ('TRAMADOL-PARACETAMOL. TABLETA. CADA TABLETA CONTIENE: CLORHIDRATO DE TRAMADOL 37.5 MG. PARACETAMOL 325.0 MG. E', 11.09)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51251005'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

-- CB-51251007 (24 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('RIVAROXABAN. COMPRIMIDO. CADA COMPRIMIDO CONTIENE: RIVAROXABAN 20 MG. ENVASE CON 28 COMPRIMIDOS.', 372.82),
  ('TOPIRAMATO TABLETA CADA TABLETA CONTIENE: TOPIRAMATO 100 MG ENVASE CON 60 TABLETAS.', 51.92),
  ('ENOXAPARINA SODICA. SOLUCION INYECTABLE CADA JERINGA CONTIENE: ENOXAPARINA SODICA 80 MG ENVASE CON 2 JERINGAS.', 243.91),
  ('PARACETAMOL SOLUCION INYECTABLE CADA FRASCO CONTIENE: PARACETAMOL 500 MG. ENVAS E CON DIEZ FRASCOS CON 50 ML.', 410),
  ('RALTEGRAVIR COMPRIMIDO CADA COMPRIMIDO CONTIENE: RALTEGRAVIR POTASICO EQUIVALENTE A 400 MG DE RALTEGRAVIR ENVA', 3180.71),
  ('COLISTIMETATO. SOLUCION INYECTABLE CADA FRASCO AMPULA CON LIOFILIZADO CONTIENE: COLISTIMETATO SODICO EQUIVALEN', 185.61),
  ('TACROLIMUS. CAPSULA. CADA CAPSULA CONTIENE: TACROLIMUS MONOHIDRATADO EQUIVALENTE A 1 MG DE TACROLIMUS. ENVASE ', 255.58),
  ('SUCRALFATO TABLETA CADA TABLETA CONTIENE: SUCRALFATO 1 G ENVASE CON 40 TABLETAS.', 23.21),
  ('QUETIAPINA TABLETA CADA TABLETA CONTIENE: FUMARATO DE QUETIAPINA EQUIVALENTE A 100 MG DE QUETIAPINA ENVASE CON', 34.9),
  ('VALPROATO DE MAGNESIO TABLETA DE LIBERACION PROLONGADA CADA TABLETA CONTIENE: VALPROATO DE MAGNESIO 600 MG ENV', 48.57),
  ('TOPIRAMATO TABLETA CADA TABLETA CONTIENE: TOPIRAMATO 25 MG ENVASE CON 60 TABLETAS.', 28.64),
  ('OCTREOTIDA SOLUCION INYECTABLE CADA FRASCO AMPULA CONTIENE: OCTREOTIDA 1 MG ENVASE CON UN FRASCO AMPULA CON 5 ', 89.89),
  ('CITALOPRAM. TABLETA. CADA TABLETA CONTIENE: BROMHIDRATO DE CITALOPRAM EQUIVALENTE A 20 MG DE CITALOPRAM. ENVAS', 10.65),
  ('PARACETAMOL SOLUCION INYECTABLE CADA FRASCO CONTIENE: PARACETAMOL 1 G. ENVASE C ON DIEZ FRASCOS CON 100 ML.', 200),
  ('RIFAXIMINA. TABLETA. CADA TABLETA CONTIENE: RIFAXIMINA 200 MG. ENVASE CON 28 TABLETAS.', 218),
  ('LACOSAMIDA. TABLETA CADA TABLETA CONTIENE: LACOSAMIDA 100 MG ENVASE CON 28 TABLETAS.', 93.96),
  ('DENOSUMAB. SOLUCION INYECTABLE. CADA JERINGA PRELLENADA CONTIENE: DENOSUMAB 60 MG ENVASE CON UNA JERINGA PRELL', 3521.58),
  ('BOSENTAN. TABLETA CADA TABLETA CONTIENE: BOSENTAN 125 MG ENVASE CON 60 TABLETAS.', 1046.73),
  ('CELECOXIB CAPSULA CADA CAPSULA CONTIENE: CELECOXIB 200 MG ENVASE CON 10 CAPSULAS.', 13.15),
  ('TAMSULOSINA. CAPSULA O TABLETA DE LIBERACION PROLONGADA CADA CAPSULA O TABLETA DE LIBERACION PROLONGADA CONTIE', 18.8),
  ('ALIMENTO MEDICO PARA PACIENTES CON ACIDEMIA METILMALONICA Y PROPIONICA, DE RECIEN NACIDOS A 7 AÑOS 11 MESES DE', 773.85),
  ('RIVAROXABAN. COMPRIMIDO. CADA COMPRIMIDO CONTIENE RIVAROXABAN DE 10 MG.', 76.83),
  ('LEUPRORELINA SUSPENSION INYECTABLE CADA FRASCO AMPULA CON MICROESFERAS LIOFILIZADAS CONTIENE: ACETATO DE LEUPR', 690),
  ('APIXABAN. TABLETA. CADA TABLETA CONTIENE: APIXABAN 5 MG. ENVASE CON 60 TABLETAS.', 812.76)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51251007'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

-- CB-51251017 (69 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('SUTURAS. SINTETICAS NO ABSORBIBLES MONOFILAMENTO DE POLIPROPILENO CON AGUJA. LONGITUD DE LA HEBRA: 75 CM CALIB', 989.77),
  ('SUTURAS. SINTETICAS ABSORBIBLES POLIMERO DE ACIDO GLICOLICO TRENZADO CON AGUJA. LONGITUD DE LA HEBRA: 67 CM CA', 332),
  ('AGUJAS HIPODERMICAS. HIPODERMICAS CON PABELLON LUER-LOCK HEMBRA DE PLASTICO DESECHABLES. LONGITUD: 32 MM. CALI', 29.09),
  ('ANTISEPTICO.GEL ANTISEPTICO ELECTROLIZADO DE SUPEROXIDACION CON PH NEUTRO INDICADO COMO AUXILIAR EN EL LAVADO ', 244.17),
  ('GUANTES. PARA EXPLORACION, AMBIDIESTRO, ESTERILES. DE POLIETILENO, DESECHABLES. TAMAÑOS: GRANDE. ENVASE CON 10', 125),
  ('GUANTES PARA EXPLORACION, AMBIDIESTRO, NO ESTERILES. DE LATEX, DESECHABLES. TAMAÑO: GRANDE. ENVASE CON 100 PIE', 71.57),
  ('INJERTOS. TUBULARES PRECOAGULADOS. 8 MM X 60 CM. PIEZA.', 19500),
  ('INJERTOS. TUBULARES, RECTOS, DE PARED REGULAR. 6 MM X 70 CM. PIEZA.', 7193.13),
  ('INJERTOS. BIFURCADOS PRECOAGULADOS. 12 X 6 MM. PIEZA.', 19500),
  ('INJERTOS. PARA PROTESIS VASCULAR. RECTOS DE PARED DELGADA, ANILLADOS AL CENTRO. 6 MM X 50 CM. PIEZA.', 13043.93),
  ('CATETERES. CATETER VENOSO CENTRAL, CALIBRE 4 FR, LONGITUD 13 CM, DE POLIURETANO O SILICON, RADIOPACO, CON DOS ', 369.17),
  ('FILTROS. PARA LEUCORREDUCIR CONCENTRADOS PLAQUETARIOS CON UNA MEDIA DE LEUCOCITOS RESIDUALES CONSISTENTEMENTE ', 1.01),
  ('COMPRESAS. PARA VIENTRE. DE ALGODON CON TRAMA RADIOPACA. LONGITUD: 70 CM. ANCHO: 45 CM. ENVASE CON 6 PIEZAS.', 50.04),
  ('EQUIPOS. DE GASTROTOMIA DE SILICON CON GLOBO EN LA PUNTA DE 5 A 10 O 20 ML CON ANILLO RETRACTOR. CALIBRE: 22 F', 600),
  ('PAÑALES. PREDOBLADOS DESECHABLES. PARA ADULTOS. PIEZA.', 7.05),
  ('SUTURAS. CATGUT CROMICO CON AGUJA. LONGITUD DE LA HEBRA: 68 A 75 CM CALIBRE DE LA SUTURA: 2-0 CARACTERISTICAS ', 247.9),
  ('CINTAS. DE FILAMENTOS DE FIBRAS POLIESTER TRENZADO LONGITUD: 30 CM ANCHO: 5 MM. ENVASE CON 12 SOBRES.', 24061.62),
  ('APOSITOS. ABSORBENTES A BASE DE ALGINATO DE CALCIO Y SODIO DE ORIGEN NATURAL. ESTERIL. TAMAÑO: DE 9.0 CM +/- 2', 39.09),
  ('INJERTOS. BIFURCADOS PRECOAGULADOS. 19 X 8 MM O 18 X 9 MM. PIEZA.', 19500),
  ('LIQUIDOS. PRESERVADOR DE CORNEA QUE CONTIENE: 2.5% DE SULFATO DE CONDROITIN DEXTRAN Y SULFATO DE GENTAMICINA. ', 1168.84),
  ('DETERGENTES O LIMPIADORES. DETERGENTE O LIMPIADOR POLIENZIMATICO NO IONICO O CATIONICO, A BASE DE ALCOHOL ISOP', 96.77),
  ('ANTISEPTICOS. LIQUIDO ANTISEPTICO, PARA LAVADO PRE Y POST QUIRURGICO DE MANOS Y PIEL. FORMULADO A BASE DE 0.75', 271.04),
  ('BOLSAS. BOLSA DE PAPEL GRADO MEDICO. PARA ESTERILIZAR CON GAS O VAPOR. CON O SIN TRATAMIENTO ANTIBACTERIANO; C', 761.79),
  ('AGUJAS HIPODERMICAS. HIPODERMICAS CON PABELLON LUER-LOCK HEMBRA DE PLASTICO DESECHABLES. LONGITUD: 38 MM. CALI', 30.84),
  ('CONECTORES. DE UNA VIA. DE PLASTICO DESECHABLES. TIPO: SIMS. DELGADO. PIEZA.', 2.47),
  ('APOSITOS, TRANSPARENTE, MICROPOROSO, AUTOADHERIBLES, ESTERILES Y DESECHABLES. MEDIDAS: 10.0 CM A 10.16 X 12.0 ', 228),
  ('CATETERES. PARA VENOCLISIS. DE FLUOROPOLIMEROS (POLITETRAFLUORETILENO FLUORETILENPROPILENO Y ETILENTRIFLUORETI', 271.07),
  ('CINTAS. PARA ESTERILIZACION EN VAPOR A PRESION. TAMAÑO: 18 MM X 50 M. ROLLO.', 31.89),
  ('SUTURAS. CATGUT CROMICO CON AGUJA. LONGITUD DE LA HEBRA: 68 A 75 CM. CALIBRE DE LA SUTURA: 0 CARACTERISTICAS D', 203),
  ('DETERGENTES O LIMPIADORES. DETERGENTE ENZIMATICO, CON ACTIVIDAD PROTEOLITICA. CONCENTRADO, PARA UTILIZARSE EN ', 135.36),
  ('ALGODONES. EN LAMINAS. ENROLLADO O PLISADO. ENVASE CON 300 G.', 40.08),
  ('JERINGAS. DE VIDRIO CON BULBO DE HULE REUTILIZABLES. CAPACIDAD: 90 ML. PIEZA.', 140.02),
  ('BOLSA DE PAPEL GRADO MEDICO. PARA ESTERILIZAR CON GAS O VAPOR. CON O SIN TRATAMIENTO ANTIBACTERIANO; CON REACT', 554.74),
  ('ESPEJOS VAGINAL DESECHABLE, MEDIANO, VALVA SUPERIOR DE 10.7 CM VALVA INFERIOR DE 12.0 CM ORIFICIO CENTRAL DE 3', 6.75),
  ('APOSITOS. ABSORBENTES A BASE DE ALGINATO DE CALCIO Y SODIO DE ORIGEN NATURAL. ESTERIL. TAMAÑO: DE 10.0 CM +/- ', 39.06),
  ('JERINGAS. DE PLASTICO SIN AGUJA CON PIVOTE TIPO LUER LOCK ESTERILES Y DESECHABLES. CAPACIDAD: 3 ML ESCALA GRAD', 69.14),
  ('JERINGAS. DE PLASTICO. CON PIVOTE TIPO LUER LOCK CON AGUJA ESTERILES Y DESECHABLES. CAPACIDAD 10 ML ESCALA GRA', 1.47),
  ('CATETERES. PARA VASOS UMBILICALES. RADIOPACOS DE CLORURO DE POLIVINILO O POLIURETANO. ESTERILES Y DESECHABLES.', 196.03),
  ('CATETERES PARA CATETERISMO VENOSO CENTRAL, DE UN LUMEN, DE ELASTOMERO DE SILICON, RADIOPACO, CON AGUJA INTRODU', 599),
  ('BOLSAS, PARA USO GENERAL, DE POLIETILENO BIODEGRADABLE. CALIBRE ENTRE 150-200. PARA LA RECOLECCION Y DESECHOS ', 152.01),
  ('ANTISEPTICOS. SOLUCION ANTISEPTICA CON GLUCONATO DE CLORHEXIDINA DE 0.5 HASTA EL 2%, ALCOHOL ETILICO O ISOPROP', 48.23),
  ('JERINGAS. DE PLASTICO, SIN AGUJA CON PIVOTE TIPO LUER LOCK, ESTERILES Y DESECHABLES. CAPACIDAD 10 ML, ESCALA G', 115.11),
  ('EQUIPOS. PARA HEMODIALISIS DE INSERCION EN SUBCLAVIA YUGULAR O FEMORAL DOBLE LUMEN, INCLUYE: - UNA CANULA. - U', 477.74),
  ('JERINGAS. JERINGA PARA INSULINA DE PLASTICO GRADO MEDICO; GRADUADA DE 0 A 100 UNIDADES CON CAPACIDAD DE 1 ML. ', 1.2),
  ('AGUJAS HIPODERMICAS. HIPODERMICAS CON PABELLON LUER-LOCK HEMBRA DE PLASTICO DESECHABLES. LONGITUD: 16 MM. CALI', 30.08),
  ('CATETERES. PARA CATETERISMO VENOSO CENTRAL, CALIBRE 7 FR X 20 CM DE LONGITUD DE POLIURETANO O SILICON, CON PUN', 167),
  ('TUBOS. PARA TORNIQUETE. DE LATEX COLOR AMBAR CON ESPESOR DE LA PARED DE 1.13 A 1.37 MM. METRO.', 13.14),
  ('CATETERES. PARA SUMINISTRO DE OXIGENO. CON TUBO DE CONEXION Y CANULA NASAL. DE PLASTICO CON DIAMETRO INTERNO D', 11.24),
  ('HEMOSTATICOS. ESPONJA HEMOSTATICA DE GELATINA O COLAGENO DE: 50 A 100 X 70 A 125 MM. ENVASE CON UNA PIEZA.', 65.33),
  ('BOLSAS. PARA UROCULTIVO (NIÑO). ESTERIL, DE PLASTICO GRADO MEDICO, FORMA RECTANGULAR, CON CAPACIDAD DE 50 ML Y', 2.4),
  ('EQUIPOS. BASICO PARA BLOQUEO EPIDURAL, CONTIENE: - AGUJA TIPO TUOHY, CALIBRE 16 O 17G, LONGITUD DE 75 A 91 MM,', 195),
  ('SOLUCION INTRA-ARTICULAR. SOLUCION ESTERIL ELASTO-VISCOSA DE APLICACION INTRA-ARTICULAR. CADA ML. CONTIENE: HI', 1500),
  ('ANTISEPTICOS. IODOPOVIDONA ESPUMA. CADA 100 ML CONTIENEN: IODOPOVIDONA 8 G. EQUIVALENTE A 0.8 G DE YODO. ENVAS', 304.75),
  ('SUTURAS SINTETICAS ABSORBIBLES, POLIMERO DE ACIDO GLICOLICO, TRENZADO, CONAGUJA. LONGITUD DE LA HEBRA. 45 CM C', 724.99),
  ('BOLSAS. PARA UROCULTIVO (NIÑA). ESTERIL, DE PLASTICO GRADO MEDICO, FORMA RECTANGULAR, CON CAPACIDAD DE 50 ML Y', 13.12),
  ('SUTURAS. SEDA NEGRA TRENZADA SIN AGUJA. LONGITUD DE LA HEBRA: 75 CM CALIBRE DE LA SUTURA: 2-0 SOBRE CON 7 A 12', 311.7),
  ('SUTURAS. SEDA NEGRA TRENZADA CON AGUJA. LONGITUD DE LA HEBRA: 75 CM CALIBRE DE LA SUTURA: 2-0 CARACTERISTICAS ', 182.21),
  ('MASCARILLAS. DESECHABLE PARA ADMINISTRACION DE OXIGENO CON TUBO DE CONEXION DE 180 CM Y ADAPTADOR. PIEZA.', 12.52),
  ('JABONES. NEUTRO ADICIONADO CON GLICERINA. PASTILLA DE 100 G. PIEZA.', 7.91),
  ('SONDAS. PARA DRENAJE URINARIO. DE LATEX CON GLOBO DE AUTORRETENCION DE 5 ML CON VALVULA PARA JERINGA. ESTERIL ', 13.3),
  ('AGUJAS. PARA RAQUIANESTESIA O BLOQUEO SUBARACNOIDEO. DE ACERO INOXIDABLE, PUNTA TIPO LAPIZ, CONECTOR ROSCADO L', 33.82),
  ('CANULAS OROFARINGEAS. DE PLASTICO TRANSPARENTE O TRANSLUCIDO. TIPO: GUEDEL/BERMAN. TAMAÑO: 5 LONGITUD: 100 MM.', 6.07),
  ('EQUIPOS. EQUIPO PARA ANESTESIA MIXTA EPIDURAL/SUBDURAL. CONTIENE: AGUJA MODELO TUOHY CALIBRE 17 G, LONGITUD 75', 728.17),
  ('SONDAS. PARA ALIMENTACION. DE PLASTICO TRANSPARENTE DESECHABLE CON UN ORIFICIO EN EL EXTREMO PROXIMAL Y OTRO E', 7.07),
  ('JERINGAS. DE PLASTICO, SIN AGUJA CON PIVOTE TIPO LUER LOCK, ESTERILES Y DESECHABLES. CAPACIDAD: 20 ML. ESCALA ', 92.39),
  ('SUTURAS. SINTETICAS ABSORBIBLES POLIMERO DE ACIDO GLICOLICO TRENZADO CON AGUJA. LONGITUD DE LA HEBRA: 67-70 CM', 180.95),
  ('PERILLA. PARA ASPIRACION DE SECRECIONES. DE HULE. NO. 4. PIEZA.', 29.32),
  ('KIT PARA ANESTESIA SUBDURAL. KIT PARA ANESTESIA SUBDURAL. CONSTA DE: 1 AGUJA WHITACRE 27G (PUNTA DE LAPIZ) CON', 1.01),
  ('APOSITOS. CON PETROLATO. MEDIDAS: 10 X 10 CM. ENVASE INDIVIDUAL. PIEZA.', 5.13)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51251017'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

-- CB-51251020 (2 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('SONDAS. SONDA PARA NUTRICION ENTERAL CON ESTILETE PUNTA DE TUNGSTENO Y GUIA DE ALAMBRE CON ADAPTADOR. LONGITUD', 289.08),
  ('EQUIPOS. DE GASTROTOMIA DE SILICON CON GLOBO EN LA PUNTA DE 5 A 10 O 20 ML CON ANILLO RETRACTOR. CALIBRE: 20 F', 600)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51251020'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

-- CB-51251021 (11 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('CATETERES GUIA MULTIPROPOSITO PUNTA CURVA A LONGITUD 100 CM. CALIBRE 8 FR. PIEZA.', 754.14),
  ('TIRAS REACTIVAS. TIRA REACTIVA. PARA DETERMINACION DE GLUCOSA EN SANGRE CAPILAR CON LIMITE DE MEDICION EN GLUC', 4.08),
  ('EQUIPO. PARA GASTROSTOMIA PERCUTANEA, DE ELASTOMERO DE SILICON. CONTIENE: BOTON CON DISPOSITIVO DE RETENCION Y', 2452.04),
  ('SISTEMA DE SUCCION, CERRADO, PARA PACIENTE CON TUBO ENDOTRAQUEAL CONECTADO A VENTILADOR, 14 FR, CONTIENE: UN T', 97.69),
  ('EQUIPOS. EQUIPO PARA DRENAJE BILIAR POR TECNICA PERCUTANEA CONSTA DE: - GUIA METALICA DE 0.038" (0.97 MM) DE D', 5702.98),
  ('ACCESORIOSMPARA MARCAPASOS. INTRODUCTOR PARA ELECTRODO DE MARCAPASO TEMPORAL. PIEZA.', 1092.15),
  ('ACCESORIOS PARA MARCAPASOS. ELECTRODO PARA MARCAPASO TEMPORAL BIPOLAR, ENDOCARDICO 5FR. PIEZA.', 1160),
  ('BATAS QUIRURGICAS. BATA QUIRURGICA CON PUÑOS AJUSTABLES Y REFUERZO EN MANGAS Y PECHO. TELA NO TEJIDA DE POLIPR', 24.16),
  ('SISTEMA DE SUCCION, CERRADO, PARA PACIENTE CON TUBO ENDOTRAQUEAL CONECTADO A VENTILADOR, 16 FR, CONTIENE: UN T', 137.01),
  ('ROPA QUIRURGICA. CAMPO SENCILLO. DE TELA NO TEJIDA DE POLIPROPILENO IMPERMEABLE A LA PENETRACION DE LIQUIDOS Y', 8.27),
  ('AGUJAS. TIPO: HUBER ANGULADA A 90 GRADOS DE ACERO INOXIDABLE PARA UTILIZARSE CON LAS CLAVES 060.303.0123 Y 060', 100)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51251021'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

-- CB-51251022 (24 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('AGUJAS PARA TOMA Y RECOLECCION DE SANGRE SENCILLA Y/O MULTIPLE ESTERILES DESECHABLES. 21 G. X 38 MM. CAJA CON ', 132.13),
  ('REACTIVOS QUIMICOS. HEMATOXILINA DE HARRIS. COLORANTE PREPARADO. FRASCO CON 1000 ML. TA.', 490),
  ('HISOPOS. HISOPO DE MANGO DE PLASTICO FLEXIBLE, DEL NUMERO CUATRO, PARA TOMA DE EXUDADO NASOFARINGEO PARA LA ID', 15.6),
  ('REACTIVOS QUIMICOS. OG-6. COLORANTE PREPARADO. FRASCO CON 1000 ML. TA.', 380),
  ('DISCOS CON ANTIMICROBIANOS. DICLOXACILINA DISCOS CON 1 MICROGRAMO. EN CARTUCHO CON 50 SENSIDISCOS PARA DISTRIB', 169.31),
  ('REACTIVOS Y JUEGOS DE REACTIVOS PARA PRUEBAS ESPECIFICAS. FUCSINA FENICADA DE ZIEHL-NEELSEN PARA TEÑIR BACILOS', 1323),
  ('TIRAS REACTIVAS. TIRA REACTIVA. PARA DETERMINACION DE GLUCOSA EN SANGRE CAPILAR CON LIMITE DE MEDICION EN GLUC', 4.08),
  ('TUBOS. DE ENSAYE; VIDRIO REFRACTARIO SIN LABIO, EN DIMENSIONES DE: 12 X 75 MM. PIEZA.', 1.19),
  ('DISCOS CON ANTIMICROBIANOS. AMPICILINA. DISCOS CON 10 MICROGRAMOS. EN CARTUCHO CON 50 SENSIDISCOS PARA DISTRIB', 1106),
  ('PRUEBAS RAPIDAS. GONADOTROFINA CORIONICA FRACCION BETA. PRUEBA RAPIDA CUALITATIVA DE UN SOLO PASO EN MEMBRANA ', 138.83),
  ('SUSTANCIAS BIOLOGICAS. ALBUMINA BOVINA, POLIMERIZADA PARA PRUEBAS EN TUBO O LAMINA EN MEDIO ALBUMINOSO PARA FA', 299),
  ('PRUEBA RAPIDA INMUNOCROMATOGRAFICA, PARA LA DETECCION CUALITATIVA DE ANTIGENOS DEL VIRUS SARS-COV-2, EN EXUDAD', 1205.5),
  ('AGUJAS. PARA TOMA Y RECOLECCION DE SANGRE SENCILLA Y/O MULTIPLE ESTERILES, DESECHABLES. 22 G. X 38 MM. CAJA CO', 129.98),
  ('MEDIOS DE CULTIVO, CALDOS. CALDO MALONATO. FRASCO CON 450 G. TA.', 4145.41),
  ('REACTIVOS QUIMICOS XILOL. RA. ACS. FRASCO CON 1000 ML. TA.', 122.44),
  ('DISCOS CON ANTIMICROBIANOS. CARBENICILINA DISCOS CON 100 MICROGRAMOS. EN CARTUCHO CON 50 SENSIDISCOS PARA DIST', 97.47),
  ('TIRAS REACTIVAS. TIRA REACTIVA PARA DETERMINACION SEMICUANTITATIVA DE GLUCOSA EN SANGRE CON LIMITES DE DETECCI', 124.5),
  ('SUSTANCIAS BIOLOGICAS. FACTOR REUMATOIDE. EQUIPO PARA SU DETERMINACION EN SUERO, COMPUESTO DE: ANTIGENO ADSORB', 590),
  ('SUSTANCIAS BIOLOGICAS ANTI AB. ANTISUERO PARA TIPIFICAR LA SANGRE DE ORIGEN MONOCLONAL. FRASCO CON 10 ML. RTC.', 163),
  ('SUSTANCIAS BIOLOGICAS. PROTEINA C REACTIVA. EQUIPO PARA INVESTIGAR POR AGLUTINACION DE PARTICULAS DE LATEX. ES', 550),
  ('DISCOS CON ANTIMICROBIANOS. GENTAMICINA DISCOS CON 10 MICROGRAMOS. EN CARTUCHO CON 50 SENSIDISCOS PARA DISTRIB', 493),
  ('CAJAS. DE CRISTAL, PARA TINCION CON CANASTILLA METALICA, PARA 50 PREPARACIONES. (PORTAOBJETOS) JUEGO CON 22 PI', 3113.73),
  ('SUSTANCIAS BIOLOGICAS. CONTROL BIOLOGICO DE ESTERILIZACION. SUSPENSION DE BACILLUS STEAROTHERMOPHILUS, EN MEDI', 29.05),
  ('TUBOS. PARA LA TOMA Y RECOLECCION DE SANGRE, POR PUNCION CAPILAR. DE POLIPROPILENO TRANSLUCIDO CON HEPARINA DE', 1139.69)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51251022'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

-- CB-51251023 (2 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('GRUPO 10 GELES CONDUCTORES PARA ESTUDIOS DE IMAGENOLOGIA. GEL CONDUCTOR. AGENTE ACUOSO PARA ULTRASONIDO Y PROC', 277.04),
  ('MEDIOS DE CONTRASTE. GRUPO 8. DE APLICACION POR VIA BUCAL O RECTAL INDICACION: ESTUDIOS DE TUBO DIGESTIVO. SUL', 52.36)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51251023'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

-- CB-51251024 (13 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('CUCHILLAS BAJO PERFIL, DESECHABLES CON ADAPTADOR PARA MICROTOMO. PARA CORTES HISTOLOGICOS EN PARAFINA. PAQUETE', 3467.03),
  ('FILTROS. PARA LEUCORREDUCIR UNA UNIDAD DE SANGRE TOTAL O PAQUETE GLOBULAR CON UNA MEDIDA DE LEUCOCITOS RESIDUA', 540),
  ('TUBOS. CONICOS DE POLIPROPILENO DE 15 ML. PIEZA.', 2.9),
  ('MEDIOS DE CULTIVO, PLACAS. PLACA DE AGAR SANGRE CON AZIDA, DESECHABLE, ESTERIL DE POLIESTIRENO CRISTAL DE 92 M', 15.83),
  ('MEDIOS DE CULTIVO, PLACAS. PLACA PARA LA CUENTA TOTAL DE HONGOS Y LEVADURAS EN LIQUIDOS. PLACA. RTC.', 9.29),
  ('TUBOS. TUBO SISTEMA PARA TOMA Y RECOLECCION DE SANGRE, DE PLASTICO PET AL VACIO (13 X 100 MM) DESECHABLE PARA ', 212.78),
  ('SUSTANCIAS BIOLOGICAS. TUBERCULINA PPD. DERIVADO PROTEICO PURIFICADO RT 23 PARA INTRADERMORREACCION. CONTIENE ', 1294.33),
  ('REACTIVOS Y JUEGOS DE REACTIVOS PARA PRUEBAS ESPECIFICAS. REACTIVO DE ERLICH. FRASCO GOTERO CON 50 ML. TA.', 47.38),
  ('REACTIVOS QUIMICOS. PARAFINA CON POLIMEROS PLASTICOS DE PESO MOLECULAR CONTROLADO CON PUNTO DE FUSION DE 56-57', 197.77),
  ('SUSTANCIAS BIOLOGICAS. EQUIPO PARA IDENTIFICACION SEROLOGICA DE STREPTOCOCCUS BETA HEMOLITICOS. A, B, C, D, E,', 5353),
  ('SUSTANCIAS BIOLOGICAS. MEDIO PARA INCLUSION DE TEJIDOS. PARA CORTES EN CONGELACION. FRASCO CON 118 ML. TA.', 520.69),
  ('TUBOS. TUBO SISTEMA PARA TOMA Y RECOLECCION DE SANGRE, DE PLASTICO PET AL VACIO (13 X 75 MM) DESECHABLE PARA A', 134.88),
  ('MEDIOS DE CULTIVO, PLACAS. PLACA PARA LA CUENTA TOTAL DE COLIFORMES EN LIQUIDOS, PARA USO EN BACTERIOLOGIA SAN', 9.29)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51251024'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

-- CB-51291007 (40 claves)
insert into contrato_servicios (contrato_id, nombre_servicio, precio_unitario)
select ct.id, v.servicio, v.precio from (values
  ('CARTUCHO DE: PEROXIDO DE HIDROGENO EN SOLUCION ACUOSA A 58%, CAPACIDAD DE 12 ML, CON IDENTIFICADOR RFID PRESEN', 382.32),
  ('EQUIPO DE VENOCLISIS DE PLASTICO GRADO MEDICO, ESTERIL, DESECHABLE, PARA USARSE EN BOMBA DE INFUSION. CONSTA D', 81.89),
  ('FLUJOMETRO DOBLE PARA OXIGENO, PARA USO MEDICO, CON ESCALA DE 0-15 LTS/MIN. CUERPO FABRICADO EN BARRA DE LATON', 1975.71),
  ('FRASCO HUMIDIFICADOR DE PLASTICO REHUSABLE CON CONEXION CGA. PRESENTACION: PIEZA. NUMERO DE CATALOGO: COD: 468', 331.09),
  ('SUJETADOR PARA CANULA ENDOTRAQUEAL, DISPOSITIVO DE FIJACION DE TUBOS ANCHOR FAST. MARCA: HOLLISTER PRESENTACIO', 252.32),
  ('CIRCUITO DE VENTILACION PEDIATRICO / NEONATAL, DESECHABLE PARA HUMIDIFICADOR FISHER & PAYKEL. PRESENTACION: CA', 7987.95),
  ('SISTEMAS CERRADOS DE SUCCION/ACCESORIOS, DESECHABLE CODO TRACH CARE NEONATAL Y PEDIATRICO, DIAMETRO EXTERNO 6 ', 300),
  ('SISTEMAS CERRADOS DE SUCCION/ACCESORIOS, DESECHABLE CODO TRACH CARE NEONATAL Y PEDIATRICO, DIAMETRO EXTERNO 8 ', 333),
  ('FRASCO DE VIDRIO TRANSPARENTE BOCA ANCHA Y TAPA DE ROSCA DE PLASTICO, CAPACIDA DE 4 LITROS, SIN GRADUAR. PRESE', 41.72),
  ('MICRONEBULIZADOR SENCILLO PARA ADULTO CON MASCARILLA Y TUBO DESECHABLE. PRESENTACION: PIEZA. NUMERO DE CATALOG', 25.02),
  ('LAPIZ BIRCHIRT PARA UNIDAD DE ELECTRIOCAUTERIO. PRESENTACION: PIEZA. NUMERO DE CATALOGO: GEBRÜDER MARTIN D7853', 33.26),
  ('PINZA ABRAZADERA UMBILICAL PARA PACIENTE RECIEN NACIDO, DE POLIPROPILENO, CON ALTA RESISTENCIA AL MOVIMIENTO Y', 8.1),
  ('SENSOR ADHESIVO PARA MEDICION DE SPO2, INFANTIL. PARA UN SOLO PACIENTE CON UN PESO MAYOR O IGUAL A 3KG Y MENOR', 315.84),
  ('JERINGA DESECHABLE DE 200ML PARA INYECCION DE LIQUIDO DE CONTRASTE CON INYECTOR DE ALTA PRESION. PRESENTACION:', 14709.69),
  ('CIRCUITO DESECHABLE PEDIATRICO/ADULTO, CON DOBLE TRAMPA DE HUMEDAD EN AMBAS RAMAS (INSPIRATORIA Y EXHALATORIA)', 268.43),
  ('CARTUCHO CON GAS DE OXIDO ETILENO AL 100%, CONTIENE 100 GRAMOS, UNIDOSIS, LICUADO, NUMERO DE CATALOGO: 4-100. ', 667.52),
  ('CABLE TRONCAL PARA SENSOR DE SPO2 REUSABLE. PRESENTACION: PIEZA. NUMERO DE CATALOGO: VCCTR. PARA SU USO EN EL ', 690),
  ('PAQUETE GRANDE: INCLUYE UNA ESPUMA DE POLIURETANO DE 400 A 600 MICRAS DE POROSIDAD DE FORMA RECTANGULAR DE 25C', 1676.1),
  ('ESPONJA ABDOMINAL PARA TERAPIA DE PRESION NEGATIVA, QUE INCLUYE: DOS BLOQUES DE ESPUMA DE POLIURETANO RETICULA', 8152.71),
  ('PARCHE ADHESIVO PARA LA FIJACION DE TUBOS DE DRENAJE Y LA PRESENTACION DE UN SELLO ADHESIVO. DIMENSIONES 7 CM ', 163),
  ('DEPOSITO DE 800 ML CON SOLIDIFICADOR. PRESENTACION: CAJA CON 5 PIEZAS. NUMERO DE CATALOGO: 66801274. PARA SU U', 2976.02),
  ('SENSOR DESECHABLE PARA SATURACION DE OXIGENO (SPO2) TIPO ADHESIVO PARA PACIENTE INFANTIL CON PESO DE 3 KG A 20', 6700),
  ('SENSOR PARA SPO2 ADHESIVO DESECHABLE PARA PACIENTE NEONATAL/ADULTO, RD SET NEO PESO MENOR QUE 3 KG O MAYOR QUE', 6700),
  ('MASCARILLA NIV CLASSICSTAR TAMAÑO L. PRESENTACION: PZA. NUMERO DE CATALOGO: MP01575. PARA SU USO EN EL EQUIPO ', 843.21),
  ('CIRCUITO DESECHABLE DE 1.8 METROS DE LONGITUD CON CABLE CALEFACTOR Y SENSOR DE TEMPERATURA, CON SUJETADOR EN F', 39985.31),
  ('SENSOR DEDAL SPO2 ADULTO REUSABLE PRESENTACION: PIEZA. NUMERO DE CATALOGO: 512D-30-90200. PARA SU USO EN EL EQ', 2023.19),
  ('SISTEMAS CERRADOS DE SUCCION/ACCESORIOS, DESECHABLE CODO TRACH CARE NEONATAL Y PEDIATRICO, DIAMETRO EXTERNO 5 ', 259.55),
  ('CABLE ADAPTADOR DE SENSOR DE OXIMETRIA (SPO2) TIPO NELLCOR, DE AL MENOS 3 MTS DE LARGO. PRESENTACION: PIEZA. N', 2899),
  ('MASCARA DE TRAQUEOSTOMIA. EN SILICON CON BANDA ELASTICA, ADULTO 12-20 PULGADAS, CONECTOR EN "T" GIRATORIO DE 3', 28.94),
  ('MICRONEBULIZADOR SENCILLO CON MASCARILLA PEDIATRICA DESECHABLE. PRESENTACION: PIEZA. NUMERO DE CATALOGO: 1886.', 25.77),
  ('RESUCITADOR PEDIATRICO DESECHABLE CON MANOMETRO, VALVULA PEEP Y VALVULA DE ALIVIO. MARCA: MERCURY MEDICAL PRES', 490.61),
  ('CABLE SPO2 DE EXTENSION, 2 MTS REUTILIZABLE. PRESENTACION: PIEZA. NUMERO DE CATALOGO: 2606487. PARA SU USO EN ', 4649.85),
  ('KIT DE ESPIROMETRIA ADULTO DESECHABLE. INCLUYE SENSOR DLITE, MANGUERA DE ESPIROMETRIA, LINEA DE MUESTREO. PRES', 9002.13),
  ('APOSITO DE ESPUMA DE ALCOHOL POLIVINILO (PVA) DIMENSIONES 10 CM X 15 CM X 0.9 CM. PRESENTACION: CAJA CON 10 PI', 2198),
  ('RESUCITADOR NEONATAL DESECHABLE CON MANOMETRO, VALVULA PEEP Y VALVULA DE ALIVIO. MARCA: MERCURY MEDICAL PRESEN', 477.18),
  ('RESUCITADOR ADULTO DESECHABLE CON MANOMETRO Y VALVULA PEEP. MARCA: MERCURY MEDICAL PRESENTACION: JUEGO. NUMERO', 481.46),
  ('ELECTRODO DE BROCHE, PARA MONITOREO CONTINUO, DESECHABLE, CON PASTA CONDUCTIVA. PRESENTACION: PAQUETE CON 100 ', 150.41),
  ('GEL PARA ULTRASONIDO. PRESENTACION: GALON. NUMERO DE CATALOGO: 97154 401400. PARA SU USO EN EL EQUIPO: CLAVE 5', 264.73),
  ('CAL SODADA GRANULAR, CON INDICADOR DE COLOR IRREVERSIBLE. PRESENTACION: CUBETA 16 KG. PARA SU USO EN EL EQUIPO', 4638.95),
  ('CABLE SENSOR SPO2 ADULTO (DEDAL) REUSABLE. PRESENTACION: 1 PIEZA. NUMERO DE CATALOGO: TS-F-D. PARA SU USO EN E', 2770)
) as v(servicio, precio) join contratos ct on ct.numero_interno='CB-51291007'
where not exists (select 1 from contrato_servicios cs where cs.contrato_id=ct.id and cs.nombre_servicio=v.servicio);

commit;