-- =====================================================================
-- SIGAF · Contrato IGSA 050GYR032N03825-055 (laboratorio clínico)
--   1) Renombra el contrato VIGENTE (30/04/2026 → 30/09/2026) a -055-01
--      (el anterior 01/05/2025 → 30/04/2026 se queda como -055-00).
--   2) Agrega columna `orden` a contrato_servicios y fija el orden de los
--      215 conceptos del contrato vigente según la lista solicitada.
-- Emparejamiento por nombre NORMALIZADO (sin acentos, minúsculas, sin signos).
-- Correr en el SQL Editor de Supabase. Idempotente.
-- =====================================================================

-- 0) Columna de orden (una sola vez, aplica a todo el catálogo)
alter table contrato_servicios add column if not exists orden int;

-- 1) Renombrar SOLO el contrato vigente a -055-01
update contratos
set numero_interno = '050GYR032N03825-055-01'
where numero_interno = '050GYR032N03825-055-00'
  and vigencia_inicio = '2026-04-30' and vigencia_fin = '2026-09-30';

-- 2) Fijar el orden de los conceptos del contrato vigente (ahora -055-01)
with c as (
  select id from contratos where numero_interno = '050GYR032N03825-055-01' limit 1
),
lista(orden, nombre) as (values
  (1,'Ácido Úrico'),
  (2,'Urea/Nitrógeno Ureico'),
  (3,'Creatinina'),
  (4,'Microalbúmina'),
  (5,'Proteínas totales'),
  (6,'Microproteínas en líquidos'),
  (7,'Albúmina'),
  (8,'Bilirrubina Directa'),
  (9,'Bilirrubinas Totales'),
  (10,'Fosfatasa Alcalina'),
  (11,'Gamma Glutamil Transferasa (GGT)'),
  (12,'Aspartato Amino Transferasa (AST)'),
  (13,'Alanina Amino Transferasa (ALT)'),
  (14,'Lactato Deshidrogenasa (DHL)'),
  (15,'Amilasa'),
  (16,'Lipasa'),
  (17,'Glucosa'),
  (18,'Colesterol'),
  (19,'Colesterol, Lipoproteínas de Alta Densidad (HDL)'),
  (20,'Triglicéridos'),
  (21,'Creatin Fosfoquinasa (CPK) Total'),
  (22,'CPK, fracción MB enzimática (CPK-MBe)'),
  (23,'Potasio'),
  (24,'Sodio'),
  (25,'Cloro'),
  (26,'Calcio'),
  (27,'Fósforo'),
  (28,'Magnesio'),
  (29,'Hierro'),
  (30,'Ferritina'),
  (31,'Transferrina'),
  (32,'Capacidad de fijación de Hierro'),
  (33,'Hemoglobina Fecal (FIT)'),
  (34,'Biometria Hematica'),
  (35,'Citometría Hemática'),
  (36,'Tiempo de Protrombina (TP)'),
  (37,'Tiempo de Tromboplastina Parcial activada (TTPa)'),
  (38,'Factor V de la coagulación'),
  (39,'Tiempo de Trombina'),
  (40,'Fibrinógeno, método de Clauss'),
  (41,'Dímero D (cuantitativo)'),
  (42,'Anticoagulante Lúpico'),
  (43,'Proteína C Antigénica'),
  (44,'Proteína S Antigénica'),
  (45,'Antitrombina'),
  (46,'Examen general de orina'),
  (47,'Gases en sangre con analitos'),
  (48,'Cultivo (sólo aislamiento)'),
  (49,'Identificación bacteriana'),
  (50,'Sensibilidad bacteriana'),
  (51,'Frasco de Hemocultivo'),
  (52,'Identificación de Levaduras'),
  (53,'Sensibilidad a Levaduras'),
  (54,'Complemento C3'),
  (55,'Complemento C4'),
  (56,'Inmunoglobulina A (IgA)'),
  (57,'Inmunoglobulina G (IgG)'),
  (58,'Inmunoglobulina M (IgM)'),
  (59,'Factor reumatoide'),
  (60,'Proteína C Reactiva, cuantitativa,'),
  (61,'Troponina I/T Semicuantitativa'),
  (62,'Péptido Natriurético B (BNP) Semicuantitativo'),
  (63,'Mioglobina, semicuantitativa en sangre total'),
  (64,'Procalcitonina Semicuantitativa'),
  (65,'Factor de crecimiento similar a la Insulina tipo 1 (IGF-1)'),
  (66,'Somatropina, Hormona del crecimiento (GH)'),
  (67,'Tirotropina, Hormona Estimulante de la Tiroides (TSH)'),
  (68,'Triyodotironina (T3) Libre'),
  (69,'Triyodotironina (T3) Total'),
  (70,'Tiroxina (T4) Libre'),
  (71,'Tiroxina (T4) Total'),
  (72,'Paratrina, Paratohormona (PTH)'),
  (73,'Corticotropina, Hormona Adrenocorticotropina (ACTH)'),
  (74,'Cortisol'),
  (75,'17-Hidroxiprogesterona'),
  (76,'Prolactina'),
  (77,'Folitropina, Hormona Estimulante del Folículo (FSH)'),
  (78,'Lutropina, Hormona Luteinizante (LH)'),
  (79,'Progesterona'),
  (80,'Estradiol (E2)'),
  (81,'Fracción beta de la H. Gonadotropina Coriónica, cuantitativa'),
  (82,'Testosterona Total'),
  (83,'Dehidroepiandrosterona (DHEA)'),
  (84,'Insulina'),
  (85,'Péptido C'),
  (86,'Colecalciferol (vitamina D3)'),
  (87,'1, 25 Dihidroxivitamina D (Vitamina D2)'),
  (88,'Antígeno CA 15-3'),
  (89,'Antígeno CA 19-9'),
  (90,'Antígeno Carcinoembrionario (CEA)'),
  (91,'Alfa 1 Feto Proteína (AFP)'),
  (92,'Antígeno CA 125'),
  (93,'Antígeno Prostático Específico Total'),
  (94,'Antígeno Prostático Específico Libre'),
  (95,'Fosfatasa Ácida'),
  (96,'Calcitonina'),
  (97,'Beta 2 Microglobulina'),
  (98,'Anticuerpos (IgG) contra Cardiolipina'),
  (99,'Anticuerpos (IgM) contra Cardiolipina'),
  (100,'Anticuerpos anti Nucleares (ANA)'),
  (101,'Anticuerpos contra Músculo Liso'),
  (102,'Anticuerpos contra Nucleosoma'),
  (103,'Anticuerpos contra Ribonucleoproteína'),
  (104,'Anticuerpos contra Ro (SS-A)'),
  (105,'Anticuerpos contra La (SS-B)'),
  (106,'Anticuerpos contra SCL-70 (Anti-topoisomerasa 1)'),
  (107,'Anticuerpos contra Insulina'),
  (108,'Anticuerpos contra Histidil-ARNt Sintetasa (Jo-1)'),
  (109,'Anticuerpos contra Smith'),
  (110,'Anticuerpos contra Mitocondria'),
  (111,'Anticuerpos contra ADN doble cadena (dsADN)'),
  (112,'Anticuerpos contra Péptido Cíclico Citrulinado'),
  (113,'Anticuerpos contra Citoplasma de Neutrófilo (ANCA), IFI'),
  (114,'Anticuerpos contra Mieloperoxidasa (p-ANCA)'),
  (115,'Antígeno 27 del HLA I grupo B (HLA-B27)'),
  (116,'Anticuerpos (IgG) contra Actina'),
  (117,'Anticuerpos contra Proteína básica de Mielina en LCR'),
  (118,'Anticuerpos contra Acetilcolina, bloqueadores de receptor'),
  (119,'Anticuerpos contra Acetilcolina, fijadores de receptor'),
  (120,'Anticuerpos contra Acetilcolina, moduladores de receptor'),
  (121,'Anticuerpos contra Tirosina Quinasa Muscular (Musk)'),
  (122,'Anticuerpos contra Gangliósido'),
  (123,'Anticuerpos (IgA) contra Endomisio'),
  (124,'Anticuerpos (IgA) contra Gliadina'),
  (125,'Anticuerpos (IgG) contra Gliadina'),
  (126,'Anticuerpos contra Islote Pancreático (ICA)'),
  (127,'Anticuerpos contra Aquaporina 4 (NMO)'),
  (128,'Anticuerpos (IgA) contra Fosfatidil Colina'),
  (129,'Anticuerpos (IgG) contra Fosfatidil Colina'),
  (130,'Anticuerpos (IgM) contra Fosfatidil Colina'),
  (131,'Anticuerpos (IgA) contra Fosfatidil Serina'),
  (132,'Anticuerpos (IgG) contra Fosfatidil Serina'),
  (133,'Anticuerpos (IgM) contra Fosfatidil Serina'),
  (134,'Anticuerpos contra células parietales'),
  (135,'Anticuerpos contra factor intrínseco'),
  (136,'Anticuerpos (IgG) contra Citomegalovirus'),
  (137,'Anticuerpos (IgM) contra Citomegalovirus'),
  (138,'Anticuerpos (IgG) contra Antígeno Temprano (EA) de Epstein Barr'),
  (139,'Anticuerpos contra Antígeno Nuclear de Epstein Barr'),
  (140,'Anticuerpos (IgG) contra cápside (VCA) de Epstein Barr'),
  (141,'Anticuerpos (IgM) contra cápside (VCA) de Epstein Barr'),
  (142,'Anticuerpos (IgG) contra Herpes virus 1 y 2'),
  (143,'Anticuerpos (IgM) contra Herpes virus 1 y 2'),
  (144,'Anticuerpos (IgM) contra Virus de la Hepatitis A'),
  (145,'Antígeno de superficie del Virus de Hepatitis B (HBsAg)'),
  (146,'Anticuerpos (IgM) contra core del Virus de Hepatitis B (anti-HBc)'),
  (147,'Anticuerpos Totales contra VHC (Anti-VHC)'),
  (148,'Anticuerpos contra VIH 1 y 2'),
  (149,'Identificación de antígenos de VIH-1 (Western blot)'),
  (150,'Anticuerpos (IgM) contra Chlamydia trachomatis'),
  (151,'Anticuerpos (IgM) contra Virus Varicela Zóster'),
  (152,'Anticuerpos (IgG) contra Rubéola'),
  (153,'Anticuerpos (IgM) contra Rubéola'),
  (154,'Anticuerpos (IgG) contra Toxoplasma gondii'),
  (155,'Anticuerpos (IgM) contra Toxoplasma gondii'),
  (156,'Anticuerpos (IgG) contra Bordetella pertussis'),
  (157,'Anticuerpos (IgM) contra Bordetella pertussis'),
  (158,'Anticuerpos (IgG) contra Virus Sincitial Respiratorio'),
  (159,'Anticuerpos (IgM) contra Virus Sincitial Respiratorio'),
  (160,'Anticuerpos contra Cisticerco'),
  (161,'Anticuerpos contra Giardia'),
  (162,'Anticuerpos (IgM) contra Helicobacter pylori'),
  (163,'Antígeno de Pneumocystis jirovecii'),
  (164,'Anticuerpos (IgM) contra Rotavirus'),
  (165,'Galactomanano'),
  (166,'Anticuerpos contra Reaginas (R.P.R./V.D.R.L.)'),
  (167,'Anticuerpos (IgG) contra Treponema pallidum'),
  (168,'Anticuerpos (IgM) contra Treponema pallidum'),
  (169,'Absorción de Anticuerpos Treponémicos Fluorescentes (FTA ABS)'),
  (170,'Prueba rápida de Antígeno de SARS-CoV-2 (nCoV-19)'),
  (171,'Sirolimus'),
  (172,'Tacrolimus'),
  (173,'Ciclosporina'),
  (174,'Ácido Micofenólico'),
  (175,'Metotrexate'),
  (176,'Ácido valproico (Valproato)'),
  (177,'Difenilhidantoína'),
  (178,'Fenobarbital'),
  (179,'Carbamacepina'),
  (180,'Digoxina'),
  (181,'Drogas de abuso, cinco analitos'),
  (182,'Litio'),
  (183,'Hemoglobina A1c'),
  (184,'Linfocitos T CD4+'),
  (185,'Identificación de mutaciones en los genes de proteasa, integrasa, transcriptasa reversa nucleósido y no nucleósido del VIH por genotipificación'),
  (186,'Detección y Genotipificación del Virus de Papiloma Humano'),
  (187,'Carga Viral de VIH'),
  (188,'Carga Viral de Hepatitis B'),
  (189,'Carga Viral de Hepatitis C'),
  (190,'Carga Viral de Citomegalovirus'),
  (191,'Carga Viral de Epstein Barr'),
  (192,'Ácido Vanililmandélico en orina, concentración 24 horas'),
  (193,'Catecolaminas Urinarias'),
  (194,'Detección del antígeno NS1 Zika'),
  (195,'Catecolaminas plasmáticas'),
  (196,'Renina'),
  (197,'Ácidos orgánicos en orina'),
  (198,'Cloruros en sudor'),
  (199,'Biotinidasa'),
  (200,'Galactosa 1 Fosfato Uridil Transferasa'),
  (201,'Galactosa'),
  (202,'Glucosa 6-Fosfato Deshidrogenasa (G6PDH)'),
  (203,'Mucopolisacáridos'),
  (204,'Tripsina (Tripsinógeno) Inmunoreactivo Neonatal (IRT Neonatal)'),
  (205,'Haptoglobina'),
  (206,'Cuantificación de Aminoácidos en suero/plasma/orina'),
  (207,'Anticuerpos (IgA) contra Beta 2 glicoproteína 1'),
  (208,'Anticuerpos (IgG) contra Beta 2 glicoproteína 1'),
  (209,'Anticuerpos (IgM) contra Beta 2 glicoproteína 1'),
  (210,'Anticuerpos (IgG) contra Membrana Basal Glomerular'),
  (211,'Anticuerpos (IgG e IgM) contra Chikungunya'),
  (212,'Inmunoglobulina D (IgD)'),
  (213,'Inmunoglobulina E (IgE)'),
  (214,'IGF unido a proteína 3 (IGFBP-3)'),
  (215,'Vasopresina, Hormona Antidiurética')
)
update contrato_servicios cs
set orden = l.orden
from lista l, c
where cs.contrato_id = c.id
  and btrim(regexp_replace(lower(translate(cs.nombre_servicio,
        'ÁÀÂÄÉÈÊËÍÌÎÏÓÒÔÖÚÙÛÜÑáàâäéèêëíìîïóòôöúùûüñ',
        'aaaaeeeeiiiioooouuuunaaaaeeeeiiiioooouuuun')), '[^a-z0-9]+', ' ', 'g'))
    = btrim(regexp_replace(lower(translate(l.nombre,
        'ÁÀÂÄÉÈÊËÍÌÎÏÓÒÔÖÚÙÛÜÑáàâäéèêëíìîïóòôöúùûüñ',
        'aaaaeeeeiiiioooouuuunaaaaeeeeiiiioooouuuun')), '[^a-z0-9]+', ' ', 'g'));

-- ============ VERIFICACIÓN ============
-- Cuántos conceptos quedaron ordenados / sin orden
select c.numero_interno,
       count(*) as total,
       count(cs.orden) as con_orden,
       count(*) - count(cs.orden) as sin_orden
from contratos c
join contrato_servicios cs on cs.contrato_id = c.id
where c.numero_interno = '050GYR032N03825-055-01'
group by c.numero_interno;

-- Conceptos del contrato que NO cruzaron con la lista (quedaron sin orden)
select cs.nombre_servicio
from contratos c
join contrato_servicios cs on cs.contrato_id = c.id
where c.numero_interno = '050GYR032N03825-055-01' and cs.orden is null
order by 1;
